config/routes.rb
Melon::Application.routes.draw do
  get "static_pages/info"

  get 'tag/:tags', to: 'posts#index', as: :tag
  resources :posts
  root to: "posts#new"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

match 'info', :to => 'static_pages#info'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :tag_list, :new_post, :name, :desc, :tag_list
  acts_as_taggable
 
   # validates :new_post, obscenity: true
   validates :new_post,  obscenity: { sanitize: true, replacement: "[Obscenity - REMOVE]" }
	
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
	  if params[:tag]
	    @posts = Post.tagged_with(params[:tag])
	  else
	    @posts = Post.all


	  end
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
		@posts = Post.all

	#@newtags = Post.all(:conditions => ["created_at >= ?", DateTime.now - 30.minutes]).order("created_at DESC").limit(1)
		@newtags = Post.where("created_at >= ?", DateTime.now - 30.seconds).order("created_at DESC").limit(1)


#@newtags = Post.where("created_at < '#{Time.now - 2.minutes.ago}'" + \
   #    " OR updated_at < '#{Time.now - 2.minutes.ago}'").order("created_at DESC").limit(1)

	#	@newtags = Post.where("created_at <= '#{Time.now - 2.days}'" + \
     #   " OR updated_at <= '#{Time.now - 3.days}'").order("created_at DESC").limit(1)

#@newtags = Post.tagged_with(params[:tag]).where("created_at >= '#{Time.now - 20.days}'" + \
 #       " OR updated_at >= '#{Time.now - 20.days}'")
	

		#@newtags = Post.all(:conditions => ["created_on >= ?", DateTime.now - 2.minutes])

	end







def create
 @post = Post.new(params[:post])
  if @post.save
	redirect_to :back, :notice => "Magic"
  	if params[:first_button] 
    flash[:alert] = "Successfully created project."
	end
	else
		render action: "new"
 	 end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/posts_helper.rb
module PostsHelper


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Melon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>
<body>

<% if notice %>
    <p class="notice"><%= notice %></p>
<% end %>

<% if alert %>
    <p class="alert"><%= notice %></p>
<% end %>

<%= yield %>




</body>

</html>

app/views/posts/_form.html.erb
	<div class="form">	


		<%= form_for @post do |f| %>
		<%= f.select(:tag_list, ['','Studying', 
			'Chewing gum', 'Running', 'Writing emails', 'Watching cartoons', 'Doodling', 'It’s the winter', 'Doing yoga', 'It’s late at night', 'It’s spring', 'Listening to music', 'At Starbucks', 'Coding', 'Reading', 'Painting', 'So much caffeine...', 'Feeling inspired', 'Meditating', 'Exercising', 'With friends', 'It’s fall', 'Drinking coffee', 'It’s sunny', 'Working in bed', 'Dancing', 'Working on a deadline', 'It’s totally silent', 'It’s early in the morning', 'Happy', 'Standing on one foot', 'Taking standardized tests', 'It’s the summer', 'Using headphones', 'It’s raining', 'Golfing', 'Shooting free throws', 'Eating', 'It’s the afternoon', 'At work', 'Chopping wood' ], {}, { :class => 'my_style_class' }) %>
		<p class="post">
		<%= f.submit "Add", :name => 'first_button' %>
	</p>
		<% end %>

<div id="add_new"> <p><span> </span> Create New</p> </div>
		<%= form_for @post do |f| %>
		 
			<div id="new_form">
		 <%= f.text_field :new_post, :placeholder => "Your Answer " %>
		</div>
		
		<p class="add_post">
		<%= f.submit "Add", :name => 'second_button'  %>
	</p>
		<% end %>

	</div>

app/views/posts/create.js.erb
$('#tag_cloud').html("<%=j render @post.new_post %>");

app/views/posts/index.html.erb
<header id="melon"><img src="header.png"> </header>

<div id="tag_cloud">
		
		<% tag_cloud Post.tag_counts, %w[s m l xl] do |tag, css_class| %>	
		<%= link_to tag.name, tag_path(tag.name), class: css_class %> 

		<% end %>
	</div>

app/views/posts/new.html.erb
<div id="loading"> </div>

<section id="content_wrap">

	<header id="melon"><img src="/assets/logo.png"> </header>

<section class="main_wrap">
<h2 class="question"> I focus best while </h2>

		<%= render 'form' %>
<div style="clear:both"></div>

</section>
<div id="tag_cloud">
		 
			
<% @newtags.each do |newtag| %>

	<%if newtag.tag_list.empty? %>	

	<%else%>	
		<div class="item_wrap personal_entry">
			<div class="item w16"><p> <%= newtag.tag_list.last %> <p></div>
			<span class="plus_tag_name"> <p> + 1  </p> </span>
				</div>
<% end %>
<% end %>
	

<% tag_cloud Post.tag_counts, %w[w1 w2 w3 w4 w5 w6 w7 w8 w9 w10 w11 w12 w13 w14 w15 w16 w17 w18 w19 w20] do |tag, css_class| %>
<div class="item_wrap">
		<span class="tag_name select_form"> <p> <%= Post.tagged_with(tag).count - 1 %> other people agree </p> </span>
		<div class="<%= "item #{css_class}" %> ">
			<%= content_tag :p, tag.name %>
		</div>

</div>
		<% end %>


	<% if Obscenity.profane?(@new_post) %>
		<!-- <div class="no-bad"><p>Let's keep it positive!</p></div> -->
	<% else %>
		<% @posts.each do |post| %>
			<% if post.new_post %>

				
					<div class="item newly_created">
					<span class="tag_name manual"> <%=post.new_post %></span>
					
				</div>
			<% else %>
			<% end %>
	<%end %>

<% end %>
	

</div>

</section>


<div id="overlay" style="display:none;">
<div id="content">

<div class="content_frame">
<div class="slide_wrap">
	<section id="one" class="slide">
<div class="mellon_image"> <img src="/assets/headband.png"></div>
<div class="summary">
	<p class="question"> <span>The Melon Headband</span>  Making the invisible activity of your brain visible and understandable.  </p>

</div>
	</section><!--Close slide 1 -->
		<section id="two" class="slide">
<div class="mellon_image"> <img src="/assets/heroshot.png"></div>
<div class="summary">
	<p class="question"> <span> Find Your Focus </span> Melon is designed to enhance the things you do in your day-to-day life. </p>
	
</div>
	</section><!--Close slide 2 -->
				<section id="three" class="slide">
<div class="mellon_image"> <img src="/assets/rundown.png"></div>
<div class="summary">
	<p class="question"> <span> Stay on Track </span> Melon tracks your focus during your important tasks and allows you to understand what helps you focus and how to focus better. </p>
	
</div>
	</section><!--Close slide 3 -->
		
</div> <!--Close slide_wrap -->
</div> <!--Close frame -->
<div id="nav_container">
<nav class="slide_thumbs"> 
<ul>
	<li> <a href="#one"></a></li>
	<li> <a href="#two"></a></li>
	<li> <a href="#three"></a> </li>
</ul>
</nav>
</div>
<div id="social_container"> <p class="kick_link"> <a href="http://www.kickstarter.com/projects/806146824/441921528?token=1b19ba14">Kickstarter </a> </p></div>

 <a class="close_overlay"></a>

</div>
</div>

<footer id="main">
	<div id="mailing_list"> <b> </b> <span> Email Signup</span> </div>
	<div class="embed_form"> 

<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="http://usemelon.us4.list-manage2.com/subscribe/post?u=38d933ed607d86f181cfed646&amp;id=be5f9ca702" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email Address" required>
	<input type="submit" value="Join" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->

	</div>
<section class="footer_wrap">
<div class="left_column">
	<div id="meet_mellon">
<img src="/assets/phone_icon.png"> <p class="meet"> Meet Melon </p> 
</div>
<p id="links" class="meet"> Share </p>
<div id="get_social"> 
	<ul>
		<li> <a href="https://twitter.com/share?url=http://www.usemelon.com" onclick="window.open(this.href);return false;"><img src="/assets/twitter.png"></a> </li>
		<li> <a target="_blank" href="http://www.facebook.com/sharer/sharer.php?u=http://www.usemelon.com"><img src="/assets/facebook.png"></a></li>
	</ul>
 </div>
</div>
<div class="right_column">
	<p class="use_us"> Use Melon and learn more about yourself in your everyday life. </p>

	<a href="http://www.kickstarter.com/projects/806146824/441921528?token=1b19ba14" class="kickstart"> Kickstarter </a>
</div>


</section>
 </footer>

app/views/static_pages/info.html.erb
<section class="content_wrap">

<div class="mellon_image"> <img src="/assets/meet_mellon.png"></div>
<div class="summary"><h3 class="intro">Meet Melon </h3>
	<p class="question"> What does your Melon look like? </p>
</div>


</section>